services:
  - type: web
    name: nestjs-app
    env: node
    plan: free

    buildCommand: npm ci && npx prisma generate && npm run build
    preDeployCommand: npm run migrate:deploy && npm run seed
    startCommand: npm run start:prod

    envVars:
      - key: NODE_VERSION
        value: "22.14.1"

      - key: DATABASE_URL
        sync: false